# Generated by Django 5.1.6 on 2025-02-14 18:12

import apps.rh.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='rh.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='rh.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='rh.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh.equipe', verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.rh.models.get_funcionario_upload_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='hierarquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='rh.hierarquia', verbose_name='Hierarquia'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh.horario', verbose_name='Horário de Trabalho'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh.loja', verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexualidade',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contratacao',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('MEI', 'MEI'), ('temporario', 'Temporário'), ('estagio', 'Estágio')], max_length=50, null=True, verbose_name='Tipo de Contratação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
