# Generated by Django 5.0.4 on 2025-02-19 15:25

import apps.rh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosfuncionario',
            name='file',
            field=models.FileField(upload_to=apps.rh.models.arquivo_upload_path),
        ),
    ]
