# Generated by Django 5.0.4 on 2025-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_alter_arquivosfuncionario_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosfuncionario',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='arquivosfuncionario',
            unique_together={('funcionario', 'titulo')},
        ),
    ]
